
import React, { useState } from 'react';
import { NutritionData } from '../types';
import MacroChart from './MacroChart';

interface NutritionCardProps {
  data: NutritionData;
  isFavorite: boolean;
  onToggleFavorite: () => void;
}

const NutritionCard: React.FC<NutritionCardProps> = ({ data, isFavorite, onToggleFavorite }) => {
  const [isShareModalOpen, setIsShareModalOpen] = useState(false);
  const [shareMessage, setShareMessage] = useState('');
  const [copyFeedback, setCopyFeedback] = useState(false);
  const [multiplier, setMultiplier] = useState<number>(1);
  const [isMetric, setIsMetric] = useState<boolean>(true);

  // Constants for conversion
  const G_TO_OZ = 0.035274;

  // Helper to scale and convert values
  const getDisplayData = (val: number, isMg: boolean = false) => {
    const scaled = val * multiplier;
    if (isMetric) {
      return {
        value: parseFloat(scaled.toFixed(1)),
        unit: isMg ? 'mg' : 'g'
      };
    } else {
      // Imperial Conversion
      if (isMg) {
        // Sodium is typically kept in mg even in US/Imperial systems
        return {
          value: parseFloat(scaled.toFixed(1)),
          unit: 'mg'
        };
      }
      // Convert grams to ounces
      return {
        value: parseFloat((scaled * G_TO_OZ).toFixed(2)),
        unit: 'oz'
      };
    }
  };

  const calories = parseFloat((data.calories * multiplier).toFixed(1));
  const protein = getDisplayData(data.protein);
  const carbs = getDisplayData(data.carbs);
  const fat = getDisplayData(data.fat);
  const fiber = getDisplayData(data.fiber);
  const sugar = getDisplayData(data.sugar);
  const sodium = getDisplayData(data.sodium, true);
  
  // Net carbs calculation
  const netCarbsVal = Math.max(0, (data.carbs - data.fiber) * multiplier);
  const netCarbs = isMetric 
    ? { value: parseFloat(netCarbsVal.toFixed(1)), unit: 'g' }
    : { value: parseFloat((netCarbsVal * G_TO_OZ).toFixed(2)), unit: 'oz' };

  const formatSummary = () => {
    const divider = '------------------------------------------';
    return `NUTRIELITE | PREMIUM NUTRITIONAL ANALYSIS
Food: ${data.foodName}
Serving: ${multiplier}x (${data.servingSize})
System: ${isMetric ? 'Metric' : 'Imperial'}
${divider}
${shareMessage ? `Personal Note: ${shareMessage}\n${divider}\n` : ''}
- CALORIES: ${calories} kcal
- PROTEIN: ${protein.value}${protein.unit}
- TOTAL CARBS: ${carbs.value}${carbs.unit}
- NET CARBS: ${netCarbs.value}${netCarbs.unit}
- TOTAL FAT: ${fat.value}${fat.unit}
- DIETARY FIBER: ${fiber.value}${fiber.unit}
- SUGARS: ${sugar.value}${sugar.unit}
- SODIUM: ${sodium.value}${sodium.unit}
${divider}
${data.description}
${divider}
Generated by NutriElite - Precision Culinary Data`;
  };

  const handleEmailShare = () => {
    const subject = encodeURIComponent(`Nutritional Insights: ${data.foodName}`);
    const body = encodeURIComponent(formatSummary());
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  const handleCopySummary = () => {
    navigator.clipboard.writeText(formatSummary()).then(() => {
      setCopyFeedback(true);
      setTimeout(() => setCopyFeedback(false), 2000);
    }).catch(err => {
      console.error('Could not copy text: ', err);
    });
  };

  const StatItem = ({ label, display, subtext }: { label: string, display: { value: number, unit: string }, subtext?: string }) => (
    <div className="flex flex-col border-b border-slate-100 py-4 last:border-0">
      <span className="text-xs uppercase tracking-widest text-slate-400 font-semibold mb-1">{label}</span>
      <div className="flex items-baseline space-x-1">
        <span className="text-2xl font-serif text-slate-900">{display.value}</span>
        <span className="text-sm text-slate-500">{display.unit}</span>
      </div>
      {subtext && <span className="text-[10px] text-amber-600 font-medium mt-1">{subtext}</span>}
    </div>
  );

  return (
    <div className="relative w-full max-w-4xl mx-auto mt-12 bg-white rounded-3xl shadow-xl overflow-hidden border border-slate-100">
      {/* Share Modal Overlay */}
      {isShareModalOpen && (
        <div className="absolute inset-0 z-50 flex items-center justify-center bg-slate-900/40 backdrop-blur-sm p-4">
          <div className="bg-white rounded-2xl p-8 max-w-md w-full shadow-2xl transform animate-in fade-in zoom-in duration-200">
            <h3 className="text-xl font-serif font-bold text-slate-900 mb-2">Share Analysis</h3>
            <p className="text-sm text-slate-500 mb-6">Include a personal note with the nutritional data.</p>
            
            <textarea
              className="w-full h-32 p-4 text-sm bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-amber-500/20 focus:border-amber-500 focus:outline-none mb-6"
              placeholder="Add a message (optional)..."
              value={shareMessage}
              onChange={(e) => setShareMessage(e.target.value)}
            />

            <div className="flex flex-col gap-3">
              <button
                onClick={handleEmailShare}
                className="w-full py-3 bg-slate-900 text-white text-sm font-semibold rounded-xl hover:bg-slate-800 transition-all flex items-center justify-center space-x-2 active:scale-[0.98]"
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
                  <path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z" />
                  <path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z" />
                </svg>
                <span>Send via Email</span>
              </button>
              
              <button
                onClick={handleCopySummary}
                className={`w-full py-3 text-sm font-semibold rounded-xl transition-all flex items-center justify-center space-x-2 active:scale-[0.98] ${
                  copyFeedback 
                    ? 'bg-emerald-50 text-emerald-700 border border-emerald-200' 
                    : 'bg-slate-100 text-slate-700 hover:bg-slate-200 border border-slate-100'
                }`}
              >
                {copyFeedback ? (
                  <>
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    <span>Copied!</span>
                  </>
                ) : (
                  <>
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
                      <path d="M8 3a1 1 0 011-1h2a1 1 0 011 1v1h1a2 2 0 012 2v10a2 2 0 01-2 2H5a2 2 0 01-2-2V6a2 2 0 012-2h1V3z" />
                    </svg>
                    <span>Copy to Clipboard</span>
                  </>
                )}
              </button>

              <button
                onClick={() => setIsShareModalOpen(false)}
                className="w-full py-2 text-slate-400 text-xs uppercase tracking-widest font-bold hover:text-slate-600 transition-colors mt-2"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}

      <div className="grid md:grid-cols-2">
        {/* Left Side: Summary & Description */}
        <div className="p-8 md:p-12 bg-slate-50">
          <div className="flex justify-between items-start mb-8">
            <div>
              <h2 className="text-3xl font-serif font-bold text-slate-900 mb-2">{data.foodName}</h2>
              <div className="flex flex-wrap items-center gap-3">
                <div className="inline-block px-3 py-1 rounded-full bg-amber-100 text-amber-800 text-xs font-bold uppercase tracking-wider">
                  Base: {data.servingSize}
                </div>
                <div className="flex items-center space-x-2 bg-white border border-slate-200 rounded-full px-3 py-1">
                  <span className="text-[10px] font-bold text-slate-400 uppercase tracking-tighter">Qty:</span>
                  <input 
                    type="number" 
                    step="0.25"
                    min="0.1"
                    value={multiplier}
                    onChange={(e) => setMultiplier(parseFloat(e.target.value) || 1)}
                    className="w-12 bg-transparent text-xs font-bold text-slate-700 focus:outline-none"
                  />
                </div>
              </div>
            </div>
            <div className="flex items-center space-x-2">
              <button 
                onClick={onToggleFavorite}
                className={`p-2.5 rounded-full border transition-all ${
                  isFavorite 
                    ? 'bg-amber-50 border-amber-200 text-amber-600 shadow-sm' 
                    : 'bg-white border-slate-200 text-slate-400 hover:text-amber-500 hover:border-amber-200'
                }`}
                title={isFavorite ? "Remove from Favorites" : "Add to Favorites"}
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fillRule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" clipRule="evenodd" />
                </svg>
              </button>
              <button 
                onClick={() => setIsShareModalOpen(true)}
                className="p-2.5 rounded-full border border-slate-200 bg-white text-slate-500 hover:text-amber-600 hover:border-amber-200 hover:shadow-sm transition-all"
                title="Share Analysis"
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path d="M15 8a3 3 0 10-2.977-2.63l-4.94 2.47a3 3 0 100 4.319l4.94 2.47a3 3 0 10.895-1.789l-4.94-2.47a3.027 3.027 0 000-.74l4.94-2.47C13.456 7.68 14.19 8 15 8z" />
                </svg>
              </button>
            </div>
          </div>
          
          <p className="text-slate-600 italic leading-relaxed mb-10 border-l-2 border-amber-600/30 pl-4">
            {data.description}
          </p>

          <div className="grid grid-cols-2 gap-8">
            <div className="flex flex-col border-b border-slate-100 py-4">
              <span className="text-xs uppercase tracking-widest text-slate-400 font-semibold mb-1">Calories</span>
              <div className="flex items-baseline space-x-1">
                <span className="text-2xl font-serif text-slate-900">{calories}</span>
                <span className="text-sm text-slate-500">kcal</span>
              </div>
            </div>
            <StatItem 
              label="Protein" 
              display={protein} 
              subtext={`${Math.round((data.protein * 4 * multiplier / (data.calories * multiplier)) * 100) || 0}% of cals`} 
            />
            <StatItem 
              label="Carbs" 
              display={carbs} 
              subtext={`${Math.round((data.carbs * 4 * multiplier / (data.calories * multiplier)) * 100) || 0}% of cals`} 
            />
            <StatItem 
              label="Total Fat" 
              display={fat} 
              subtext={`${Math.round((data.fat * 9 * multiplier / (data.calories * multiplier)) * 100) || 0}% of cals`} 
            />
          </div>
        </div>

        {/* Right Side: Detailed Stats & Chart */}
        <div className="p-8 md:p-12 bg-white flex flex-col justify-between">
          <div className="mb-8">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-sm uppercase tracking-[0.2em] text-slate-400 font-bold">Macro Distribution</h3>
              <div className="flex bg-slate-100 p-1 rounded-lg">
                <button 
                  onClick={() => setIsMetric(true)}
                  className={`px-3 py-1 text-[10px] font-bold rounded-md transition-all ${isMetric ? 'bg-white shadow-sm text-slate-900' : 'text-slate-400 hover:text-slate-600'}`}
                >
                  METRIC
                </button>
                <button 
                  onClick={() => setIsMetric(false)}
                  className={`px-3 py-1 text-[10px] font-bold rounded-md transition-all ${!isMetric ? 'bg-white shadow-sm text-slate-900' : 'text-slate-400 hover:text-slate-600'}`}
                >
                  IMP
                </button>
              </div>
            </div>
            <MacroChart data={{ ...data, protein: protein.value, carbs: carbs.value, fat: fat.value }} />
          </div>

          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-sm uppercase tracking-[0.2em] text-slate-400 font-bold">Additional Details</h3>
              <span className="text-[10px] text-slate-300 font-mono">SCALED VALUES</span>
            </div>
            
            <div className="bg-slate-50/50 rounded-2xl border border-slate-100 overflow-hidden">
              <div className="flex justify-between items-center px-5 py-4 border-b border-slate-100 hover:bg-white transition-colors">
                <div className="flex flex-col">
                  <span className="text-sm font-semibold text-slate-700">Dietary Fiber</span>
                  <span className="text-[10px] text-slate-400 uppercase tracking-tighter">Digestion Support</span>
                </div>
                <span className="font-serif text-xl text-slate-900">{fiber.value}<span className="text-sm font-sans text-slate-400 ml-0.5">{fiber.unit}</span></span>
              </div>

              <div className="flex justify-between items-center px-5 py-4 border-b border-slate-100 hover:bg-white transition-colors">
                <div className="flex flex-col">
                  <span className="text-sm font-semibold text-slate-700">Total Sugars</span>
                  <span className="text-[10px] text-slate-400 uppercase tracking-tighter">Energy Glycemic</span>
                </div>
                <span className="font-serif text-xl text-slate-900">{sugar.value}<span className="text-sm font-sans text-slate-400 ml-0.5">{sugar.unit}</span></span>
              </div>

              <div className="flex justify-between items-center px-5 py-4 border-b border-slate-100 hover:bg-white transition-colors">
                <div className="flex flex-col">
                  <span className="text-sm font-semibold text-slate-700">Sodium</span>
                  <span className="text-[10px] text-slate-400 uppercase tracking-tighter">Electrolyte balance</span>
                </div>
                <span className="font-serif text-xl text-slate-900">{sodium.value}<span className="text-sm font-sans text-slate-400 ml-0.5">{sodium.unit}</span></span>
              </div>

              <div className="flex justify-between items-center px-5 py-4 bg-amber-50/30 hover:bg-amber-50 transition-colors">
                <div className="flex flex-col">
                  <span className="text-sm font-bold text-amber-800">Net Carbs</span>
                  <span className="text-[10px] text-amber-600/70 uppercase tracking-tighter">Carbs - Fiber</span>
                </div>
                <span className="font-serif text-xl text-amber-900">{netCarbs.value}<span className="text-sm font-sans text-amber-600/50 ml-0.5">{netCarbs.unit}</span></span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default NutritionCard;
